//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bank
    {
        [Key]
        [Required] [RegularExpression("[A-Za-z]{4,5}[0-9]{2}",ErrorMessage ="Incorrect pattern")]
        public string AccountNumber { get; set; }
        [Required] [MaxLength(10,ErrorMessage ="Length should be maximum of 10 chars")]
        public string Username { get; set; }
        [Required] [MinLength(3,ErrorMessage ="Legth should be of minimum 3 chars")]
        public string Password { get; set; }
        [Required]
        public string AccountType { get; set; }
    }
}
